language: java
jdk:
  - openjdk8

install:
  - mvn install -DskipTests
  - mvn test -Djavax.xml.bind.context.factory=org.eclipse.persistence.jaxb.JAXBContextFactory

script:
  - bash scripts/gitbook.sh
